---
title: "Untitled"
author: "Winson & Daniel"
date: "2023-12-13"
output: html_document
---

#Library
```{r}
library(dplyr)
library(tidyr)
library(caret)
library(shiny)
library(shinythemes)
library(rpart)
library (e1071)
library(randomForest)
```

## A.Data Loading dan Preprocessing
# 1. Load Dataset
```{r}
# CP = Calon Pendaftar
CP = read.csv('profiling.csv', sep = ";")
CP
str(CP)

# HK = Hasil Kelulusan
HK = read.csv('admisi.csv', sep = ";")
HK
str(HK)
```
# 2. Merge Dataset, Check missing value, Duplicate, Outlier
```{r}
# merge data
Data = merge(CP, HK, by = "ID")
Data
str(Data)

anyNA(Data)
anyDuplicated(Data)

# remove duplicate
Data = unique(Data)
str(Data)
Data

# labeling Riset
Data <- Data %>%
  na.omit() %>%
  mutate(RISET = ifelse(RISET == "Ya", 1, 0)) %>%
  mutate(RISET = as.numeric(RISET))

# labeling Jenis kelamin
Data$JENIS_KEL [Data$JENIS_KEL == " L"] = 1 
Data$JENIS_KEL [Data$JENIS_KEL == " P"] = 2
Data$JENIS_KEL = as.numeric(Data$JENIS_KEL)

# cleaning IPK
Data = Data %>%
  mutate(IPK = gsub("," , "." , IPK)) %>%
  mutate(IPK = as.numeric(IPK)) %>%
  mutate(IPK = ifelse(IPK > 4, NA, IPK)) %>%
  na.omit() 

# cleaning Surat Rekomendasi & Motivation Letter
Data = Data %>%
  mutate(MOT_LETTER =  gsub("," , "." , MOT_LETTER)) %>%
  mutate(REKOM_LETTER =  gsub("," , "." , REKOM_LETTER)) %>%
  mutate(MOT_LETTER = as.numeric(MOT_LETTER)) %>%
  mutate(REKOM_LETTER = as.numeric(REKOM_LETTER)) 

Data = Data %>%
 mutate(MOT_LETTER = ifelse(MOT_LETTER > 5 | MOT_LETTER < 1, NA, MOT_LETTER)) %>%
  mutate(REKOM_LETTER = ifelse(REKOM_LETTER > 5 | REKOM_LETTER < 1, NA, REKOM_LETTER)) %>%
  na.omit()

Data

# Feature Selection
Data = Data %>%
  select(-ID) %>%
  select(-NAMA) 
  
```

# 5. Simple Randomsplit Training Testing 80:20
```{r}
set.seed(123)
split = sample(nrow(Data), size = 0.8 * nrow(Data), replace = F)
training = Data[split,]
testing = Data[-split,]
```

# B. Modeling dan Evaluasi
# Model 1 (Logistic Regression)
```{r}
model1 = glm(LULUS ~., data=training, family = "binomial")

summary(model1)
saveRDS(model1, file="model1.rds")

# testing accuracy
probs = predict(model1, newdata=testing, type="response")
accuracy = mean(testing$LULUS == as.numeric(probs>0.5))
print(accuracy)

testing$LULUS <- as.factor(testing$LULUS)
predicted <- as.factor(as.numeric(probs > 0.5))
confusionMatrix(testing$LULUS, predicted)
```

# Model 2 (Binary Tree)
```{r}
model2 = rpart(LULUS ~., data=training, method="class")

probs2 = predict(model2, newdata = testing, type = "class")

dim(probs2)
confusionMatrix(probs2, testing$LULUS)
saveRDS(model2, file="model2.rds")
```
# Model 3 (Support Vector Machine)
```{r}
model3 = svm(LULUS ~ ., data = training, kernel = 'polynomial', cost = 1e8)

probs3 = predict(model3, newdata = testing)

svm.accuracy = mean(testing$LULUS == as.numeric(probs3>0.5))
print(svm.accuracy)

testing$LULUS <- as.factor(testing$LULUS)
svm.predicted <- as.factor(as.numeric(probs3 > 0.5))
confusionMatrix(testing$LULUS, svm.predicted)
saveRDS(model3, file="model3.rds")
```
# Model 4 (Random Forest)
```{r}
model4 = randomForest(LULUS ~ ., data = training)

probs4 = predict(model4, newdata = testing)

rf.accuracy = mean(testing$LULUS == as.numeric(probs4>0.5))
print(svm.accuracy)

testing$LULUS <- as.factor(testing$LULUS)
rf.predicted <- as.factor(as.numeric(probs4 > 0.5))
confusionMatrix(testing$LULUS, rf.predicted)
saveRDS(model4, file="model4.rds")
```
# Shiny
```{r}
# UI
library(shiny)
library(shinythemes)

ui <- fluidPage(
  theme = shinytheme("flatly"),  # Terapkan tema Bootstrap

  navbarPage(
    "IEDU Prediction Tool",  # Judul aplikasi di navbar

    tabPanel("Prediksi",  # Buat tabPanel untuk konten aplikasi
      div(
        style = "display: flex; justify-content: center; flex-end: center; height: 100vh;",
        div(
          style = "width: 1000px; padding: 20px; background-color: #ffffff; border-radius: 10px; margin: 0 auto;",
          sidebarLayout(
            sidebarPanel(
              # Input fields
              selectInput("MODEL", "Model Prediksi", choices = c("Logistic Regression", "Binary Tree"), selected = NULL),
              selectInput("JENIS_KEL", "Jenis Kelamin", choices = c("Laki-laki", "Perempuan"), selected = NULL),
              numericInput("USIA", "Usia", value = NULL, min = 0),
              numericInput("Ranking_Uni_Asal", "Ranking Universitas Asal", value = NULL, min = 0),
              numericInput("IPK", "IPK", value = NULL, min = 0, max = 4),
              selectInput("RISET", "Apakah Melakukan Riset?", choices = c("Ya", "Tidak"), selected = NULL),
              numericInput("GRE", "GRE", value = NULL, min = 0),
              numericInput("TOEFL", "TOEFL", value = NULL, min = 0),
              numericInput("MOT_LETTER", "Motivation Letter", value = NULL, min = 0, max = 5),
              numericInput("REKOM_LETTER", "Recommendation Letter", value = NULL, min = 0, max = 5)
            ),
            mainPanel(
              # Output
              actionButton("submit", "Submit", class = "btn-primary"),
              textOutput("prediksi")
            )
          )
        )
      )
    )
  )
)



# Server
server = function(input, output) {
 values = reactiveValues(
  JENIS_KEL = NA,
  RISET =NA,
  USIA = NA,
  IPK = NA,
  Ranking_Uni_Asal = NA,
  GRE = NA,
  TOEFL = NA,
  MOT_LETTER = NA,
  REKOM_LETTER = NA
 )
 
model1 = readRDS("model1.rds")
model2 = readRDS("model2.rds") 
 
observeEvent(input$submit, {
values$JENIS_KEL = ifelse(input$JENIS_KEL == "Laki-laki", 1, 2)
values$RISET = ifelse(input$RISET == "Ya", 1, 0)  
  
  # Create data frame for prediction
data_for_prediction = data.frame(
  JENIS_KEL = values$JENIS_KEL,
  RISET = values$RISET,
  USIA = input$USIA,
  IPK = input$IPK,
  Ranking_Uni_Asal = input$Ranking_Uni_Asal,
  GRE = input$GRE,
  TOEFL = input$TOEFL,
  MOT_LETTER = input$MOT_LETTER,
  REKOM_LETTER = input$REKOM_LETTER
)
  
  if (input$MODEL == "Logistic Regression") {
   probs = predict(model1, newdata = data_for_prediction, type = "response")
   prediksi = ifelse(probs > 0.5, 1, 0)
  } else if (input$MODEL == "Binary Tree") {
   probs = predict(model2, newdata=data_for_prediction, type="class")
   prediksi = probs
  }

# Display results as "Lulus" or "Tidak lulus"
  output$prediksi = renderText({
   paste("Hasil Prediksi:",ifelse(prediksi==1, "Lulus", "Tidak lulus"))
  })
 })
}

# Run the app
shinyApp(ui, server)


```